### PR TITLE
NEUR1630 Github Dependency

### PR DESCRIPTION
**Pull request by anna-murphy**
Adds `git+https://github.com/alleninstitute/abc_atlas_access.git` as a dependency in requirements.txt for the NEUR1630 image.

### CODE REVIEW

**Comment by anna-murphy** [comment]
@digicosmos86 Might need to call in some help on this one... I've added the appropriate line to the requirements.txt file, but it looks like it can't find the repository when building it in the github action. If I do it locally, I _can_ install it however.

```bash
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip -U install git+https://github.com/alleninstitute/abc_atlas_access.git
```

I also know that you can install through a requirements.txt like this because it's how I wrote the TC Cloud Model package. Any thoughts why the Github Action runner wouldn't be able to find this?

**Comment by digicosmos86** [comment]
> @digicosmos86 Might need to call in some help on this one... I've added the appropriate line to the requirements.txt file, but it looks like it can't find the repository when building it in the github action. If I do it locally, I _can_ install it however.
> 
> ```shell
> $ python3 -m venv .venv
> $ source .venv/bin/activate
> $ pip -U install git+https://github.com/alleninstitute/abc_atlas_access.git
> ```
> 
> I also know that you can install through a requirements.txt like this because it's how I wrote the TC Cloud Model package. Any thoughts why the Github Action runner wouldn't be able to find this?

Okay it's because the requirement.txt is actually installed by conda/mamba, which do not support installing from git. Looking for solutions, Hold on a sec

**Comment by digicosmos86** [comment]
Oh @anna-murphy you can actually add it to `requirements.pip.txt`, and then the package will be installed with pip. Let me know if this works

**Comment by anna-murphy** [comment]
Good catch! This is good to merge whenever~

**Review by digicosmos86 — APPROVED** [review]
LGTM!

**Pull request merged**
